spring:
  application:
    name: servicio-cursos

server: 
  port: 8081

eureka:
  instance: 
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka